export const ADD_ALL_USERS = 'ADD_ALL_USERS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const SET_USER_TO_EDIT = 'SET_USER_TO_EDIT';
export const ADD_EDITED_STATE = 'ADD_EDITED_STATE';